#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

# Activate quantification env to solve vtkplotter versioning
source /opt/conda/etc/profile.d/conda.sh
conda activate quantification

python -u run_capsule.py "$@"