FROM continuumio/miniconda3:23.9.0-0

ARG DEBIAN_FRONTEND=noninteractive

# Necessary for vtkplotter
RUN apt-get update && apt-get install libgl1 git -y
RUN apt-get install libxrender1

# vtkplotter works properly on python 3.9
RUN conda create -n quantification python=3.9 -y
SHELL ["conda", "run", "-n", "quantification", "/bin/bash", "-c"]

# aind-ng-link==1.0.6 \
RUN pip install -U --no-cache-dir \
    numpy==1.24.0 \
    dask[distributed]==2022.11.1 \
    scikit-learn==1.5.1 \
    imlib==0.1.3 \
    git+https://github.com/AllenNeuralDynamics/aind-ng-link.git \
    tqdm==4.65.0 \
    antspyx==0.5.4 \
    argschema==3.0.4 \
    ray==2.9.0 \
    pims==0.6.1 \
    xmltodict==0.13.0 \
    neuroglancer==2.36 \
    boto3==1.26.112 \
    vedo==2023.4.6 \
    aind-data-schema==1.0.0